bioperl/bioperl-live

- Bio/PrimarySeqI.pm
- t/Seq/Seq.t
Using clone() in Bio::PrimaryI->trunc() on a Bio::Seq::RichSeq type has an unintended consequence of cloning the entire sequence, including features outside the target range. See issue #83
> Add Bio::Seq::RichSeq to trunc() for not using clone()

- Bio/SeqIO/embl.pm
- t/SeqIO/embl.t
- t/data/test_space.embl
This makes /product= "some long ... value" read as if the space
after the '=' was not there; this formatting has been observed
in the wild.
As discussed on the mailing list: http://thread.gmane.org/gmane.comp.lang.perl.bio.general/27453
> Accept space after equal sign in qualifiers when reading EMBL.

- Bio/AlignIO/stockholm.pm
With the previous code, the name of a sequence can be attached to "AC" if it is 22 (or more) characters long
fix: make sure there is at least 1 space between the sequence name and the "AC" tag
> Bugfix in the Stockholm AlignIO writer

- Bio/SeqIO/entrezgene.pm
$seq is decalared at line 151 so that it doesn't have to be passed as an argument to subs. However, at line 199, in the next_seq sub, $seq is declared again such that the original $seq variable is never defined. As far as I can tell this works in practice because for the most part $seq is only accessed in the next_seq sub. However, if you run into a variable without a tagname and try to throw the warning at line 571 your script dies with an error when trying to call method 'id' on an undefined variable. This suggested fix is simply to stop re-declaring $seq at line 199.
> Stop masking $seq variable in entrezgene.pm next_seq

- Bio/DB/SeqFeature/Store/DBI/SQLite.pm
- scripts/Bio-DB-SeqFeature-Store/bp_seqfeature_load.pl
Several of our GBrowse instances had issues with full-text (attribute) searches timing out. Profiling revealed that the execution time of Bio::DB::SeqFeature::Store::search_attributes on our Bio::DB::SeqFeature::Store::DBI::SQLite databases contributed significantly to this problem. The proposed changes, which add support for indexing the attribute table using SQLite's FTS (full-text search) extension, resolved the issue (when used in conjunction with Scott Cain's recent commit that removed the use of CGI::Pretty in GBrowse: https://github.com/GMOD/GBrowse/commit/298cab3ece8f68b7baf2e9d085fab9055772fa3c)
To demonstrate the performance impact of an FTS attribute table on search_attributes(), consider the following script:
```
use strict; use warnings;
use Bio::DB::SeqFeature::Store;
my $db …
```
> Support FTS attribute table and WITHOUT ROWID optimization for Bio::DB::SeqFeature::Store::DBI::SQLite

- scripts/utilities/bp_find-blast-matches.pl
Added a personal script to extract a DNA sequence from a FASTA file using a BLAST output file.
Expects at least two arguments, the BLAST file and the FASTA file.  There are a number of optional arguments that are explained in the script.
This script is especially useful when trying to extract sequences with variance (hence the BLAST search beforehand) from FASTA files.
For example, say that you are trying to extract a given gene and 2000 base pairs 5' to it from 20 different genomes.  All you have is one gene sequence, however.  By doing a BLAST search between each of the genomes and the gene and then using this script, you can extract the sequences that you are interested in.
The script also has options to extract a specified 3' or 5' sequence from the FASTA file, as well as an e-value …
> Added script to extract DNA sequences (as well as 5' or 3' regions if specified) from a FASTA file using a BLAST output file

- Bio/SearchIO/fasta.pm
Hello,
I've bumped on a problem where bioperl hangs when reading an output generated by fasta36.
Here's an example: http://karasik.eu.org/misc/fasta.txt
Seems that the problem is with fasta36 (vs fasta34) adds >>><<< and >>>/// markings that don't go well with bioperl.
Sincerely,
Dmitry
> don't hang on parsing fasta36 -m 9 output

- Bio/Tools/Alignment/Consed.pm
redeclaration of my is deprecated in perl 5.23.2. This causes t/Tools/Alignment/Consed.t  to fail:
```
Failed test 'use Bio::Tools::Alignment::Consed;'
at t/Tools/Alignment/Consed.t line 19.
Tried to use 'Bio::Tools::Alignment::Consed'.
Error:  Can't redeclare "my" in "my" at Bio/Tools/Alignment/Consed.pm line 1712, at end of line
```
Removal of my redeclaration fixes error and allows test to pass.
> remove my redeclaration that fails with perl 5.23.2

- Bio/Align/Utilities.pm
- t/Align/Utilities.t
for aa_to_dna_aln - use the display id for to the DNAseq object not the key in the hash which links proteins to DNA when making then new DNA (well CDS) alignment object.
> fix IDs per Issue #137 when making DNAaln objects

- Bio/SearchIO/hmmer3.pm
- t/SearchIO/hmmer.t
- t/data/phmmer.out
Currently SearchIO::hmmer3 skips all lines when parsing phmmer output - but at first glance, the format looks very similar (identical?) to hmmsearch. I've added a few tweaks to enable phmmer output to be parsed like hmmsearch and a test to check that the output looks vaguely sensible.
> Allow SearchIO::hmmer3 to parse output from phmmer

- Bio/OntologyIO/obo.pm
The [Disease Ontology OBO file](http://purl.obolibrary.org/obo/doid.obo) is causing issues for the Bio::OntologyIO::obo parser due to the use of URLs in the def line attributions.  For example, the term angiosarcoma below is parsed so that the def line URLs result in an array of DBLink objects with the database set to 'url' and primary_id set to 'http'.
```
[Term]
id: DOID:0001816
name: angiosarcoma
alt_id: DOID:267
alt_id: DOID:4508
def: "A malignant vascular tumor that results_in rapidly proliferating, extensively infiltrating anaplastic cells derived_from blood vessels and derived_from the lining of irregular blood-filled spaces." [url:http\://emedicine.medscape.com/article/276512-overview, url:http\://en.wikipedia.org/wiki/Hemangiosarcoma, …
```
> Fix for the Disease Ontology OBO file 'def' lines

- Bio/Tools/SiRNA/Ruleset/tuschl.pm
- t/Tools/SiRNA.t
In Perl 5.24.0, when running t/Tools/SiRNA.t, we were getting the warning
above on two consecutive lines.  This patch silences those warnings and
prevents the module from failing on future versions of perl.
> Avoid "Unescaped left brace in regex is deprecated" warning.

- t/RemoteDB/SeqVersion.t
The values returned from NCBI apparently changed (`dead` is now `suppressed`), so need to change the expected values for the test. Part of addressing #160.
> Fixes remote seqversion tests.

- t/RemoteDB/Taxonomy.t
The NCBI taxonomy changed, and thus the query results expected in some of the tests here would no longer match. Part of addressing #160.
> Fixes remote taxonomy tests

- .travis.yml
- travis_scripts/trigger-dockerhub.sh
This introduces the mechanism to use the Docker Hub API to trigger automatic rebuilds of the [bioperl/bioperl](https://hub.docker.com/r/bioperl/bioperl/) images. Tag `latest` is triggered if the build is for `master` (identified as not a pull request and not a tag), and only for the Perl version also used on the Docker image.
> Adds support for automatic rebuild of Docker images

- .travis.yml
It seems that tags would be matched by the branch whitelist if added there, so let's try this here.
> Includes tags patterned after release in Travis builds

- travis_scripts/trigger-dockerhub.sh
Limits triggering the rebuild of Docker Hub `latest` image to the master branch. 
Also adds some comments to make it clearer what conditions are acted upon.
> Limit Docker Hub trigger

- INSTALL.md
This required some minor restructuring to fit it into the current documentation, mainly decrementing the level of the headings for installing locally.
Closes #180.
> Adds instructions for installing BioPerl as a Docker image.

- Bio/Tools/CodonTable.pm
- t/SeqTools/CodonTable.t
- is_ter_codon was incorrectly returning ambiguous codons as stop codons (ie. NNN was being returned true), any failure in the list of unambiguous codons should return false, the opposite was occuring
- U was not being remapped to T, it's needed for UAG and such
- Added tests for better coverage of corner cases
> Ambiguous codons being returned as stop codons

- Bio/SeqIO/embl.pm
- Bio/Tools/CodonTable.pm
- t/SeqTools/CodonTable.t
Hello,
There seems to be another corner case for the already fixed issue, which I'm submitting now; it's rather trivial and is addressed in 7d728ce.
However github insists on dragging in two unrelated commits  44c3078 and  5c47b07 , that already seem to be present as 260ebb9 and d56580d in the master branch, and I cannot figure out what's going on, and can neither create a pull request without these two - please take a look.
Sincerely,
Dmitry
> address another case in #190

- Bio/SeqIO/embl.pm
When writing several times an Bio::Seq object (containing SeqFeatures) with SeqIO::embl it yields to shuffle each time the order of the qualifiers for each feature, even if the Bio::Seq object is not modified between each trial. This comes from the fact that hashes keys in perl are not ordered.
This can be fixed by sorting the keys before writing features in embl.pm, line 956.
This is not a critical issue, but this fix can help to produce more robust and comparable files (I discovered this issue by making functional tests on a personal project that use BioPerl: it was impossible to produce twice the same files with the same data...).
Note: the first commit comes from a bug from my IDE that had unnecessary indentations on 22 lines.
> Sorting qualifiers while write embl files

- Bio/DB/SeqFeature/Store/DBI/SQLite.pm
When FTS is specified, Bio::DB::SeqFeature::Store::DBI::SQLite attempts to use the newest supported FTS. DBD::SQLite has supported FTS5 since 1.51_01; however, the CREATE VIRTUAL TABLE statement results in an error like the following:
> DBD::SQLite::db do failed: parse error in "id integer not null" at /usr/local/lib/perl5/site_perl/Bio/DB/SeqFeature/Store/DBI/SQLite.pm line 436.
This code previously worked in [FTS3/FTS4](https://www.sqlite.org/fts3.html), where column types were optional in the CREATE VIRTUAL TABLE statement:
> If column names are explicitly provided for the FTS table as part of the CREATE VIRTUAL TABLE statement, then a datatype name may be optionally specified for each column. This is pure syntactic sugar, the supplied typenames are not used by FTS or the SQLite core …
> Support FTS5 in Bio::DB::SeqFeature::Store::DBI::SQLite

- .travis.yml
The Travis CI build was previously failing on perl v5.24 (for example, [here](https://travis-ci.org/bioperl/bioperl-live/jobs/221983501)).
> Travis CI: Add Test::Most dependency

- t/RemoteDB/Taxonomy.t
The test requires the network and was failing on a Travis CI build that I ran on my account [here](https://travis-ci.org/zmughal/bioperl-live/jobs/221986832#L2535) and on this repository [here](https://travis-ci.org/bioperl/bioperl-live/jobs/221991748#L2546).
I also made some fixes so that variables are only declared once.
> Fix test RemoteDB/Taxonomy.t: requires networking

- .travis.yml
- t/RemoteDB/Taxonomy.t
This replaces the manual configuration.
See <https://github.com/travis-perl/helpers>.
---
Split coverage into separate builds
This allows for the coverage to run separate test files in each build and the
final result is merged on Coveralls. The reason for the split is that running
the coverage on all test files causes Travis CI to time out since it can
sometimes take over the 49 minute limit.
---
`BIOPERL_NETWORK_TESTING` can be enabled if anyone wants to run the network
tests on a separate branch.
> Use Travis Perl helper script and enable coverage

- .travis.yml
This is a PR of what was discussed on the mailing list and in <https://github.com/bioperl/bioperl-live/issues/224>. In order to activate the changes, the cron job feature must be activated as follows under [Travis CI settings for bioperl-live](https://travis-ci.org/bioperl/bioperl-live/settings):
after creating a branch called `network-cron-master`.
I have been running the network tests [on my own fork of the repo and it has been failing](https://travis-ci.org/zmughal/bioperl-live/builds), so they can be used to identify areas that can be worked on.
> Use a Travis cron job for network tests

- travis_scripts/trigger-dockerhub.sh
Apparently COVERAGE gets set (to a non-empty value) even if not defined as `COVERAGE=1` in the build environment.
I don't know where the underlying script (`coverage-setup`) is to verify, but I hope it doesn't get set to something other than `0`. @zmughal can you check?
> Fixes test for running code coverage

- Bio/DB/SeqFeature/Store/GFF3Loader.pm
Bio::DB::SeqFeature::Store::GFF3Loader adds the undocumented attribute _parent_id_ to the resulting Bio::DB::SeqFeature::Store database. This attribute, which is not referenced anywhere else in the code, is added in a section of code labeled "TEMPORARY HACKS TO SIMPLIFY DEBUGGING". 
Since this attribute can take up non-trivial space in the attribute table, depending on the GFF (e.g., I just checked a gene model GFF from NCBI that was run through GFF3Loader via bp_seqfeature_load.pl, and there were 83,590 parent_id rows in the attribute table---and these are indexed as well), it could provide modest space savings & search performance improvements to omit the parent_id attribute (or comment-out for posterity, or set only if a DEBUG constant is set).
On a related note, I tend to manually …
> Omit unnecessary parent_id attribute added by GFF3Loader

- Bio/DB/IndexedBase.pm
Fixes <https://github.com/bioperl/bioperl-live/issues/250>.
See [this build log for perl 5.24](https://travis-ci.org/zmughal/bioperl-live/jobs/274671546)
to confirm.
> Change `or` to `||` to fix precedence warning

- Bio/DB/Flat/BinarySearch.pm
self->throw is called instead of $self->throw, so module does not seem to throw an error if the primary index file is not readable
> Fixed call to self instead of $self

- lib/Bio/Tree/Statistics.pm
- t/Tree/TreeStatistics.t
I found that in `assess_bootstrap()`, that the denominator in the bootstrap calculation had an off-by-one error.
Also: I added a very simple test for `assess_bootstrap()` in `t/Tree/TreeStatistics.t`.
> fixed bootstrapping bug where no bootstrap could have been 100 percent

- lib/Bio/DB/Fasta.pm
- lib/Bio/DB/IndexedBase.pm
- lib/Bio/DB/Qual.pm
Bio::DB::IndexedBase::_strip_crnl calls Inline::C in an eval statement and does runtime compilation of a C function. The eval statement sometimes does not work and can generate other issues with modules that call Inline::C internally. The C based method for the perl code was apparently done for performance reasons, but perl's native tr (translator) operator gives similar performance without the weird C compilation baggage associated with Inline::C. Also using the operator directly rather than calling _strip_crnl as a function avoids copying the string with each function call.
I have both removed the function _strip_crnl and replaced all locations where it is used with translator operations.
> replacing all calls to Bio::DB::IndexedBase::_strip_crnl with native perl tr operator

- lib/Bio/Tools/CodonTable.pm
[BUG] Table 0 (strict) was shifted in table 1, because when `$id` has value `0`  the following test is false `$id = 1 if (  $id ) );`.  Fixed by changing if statement which now accepts  `0` as value;
> Fix Codon Table 0 (strict) that was not selectable

- lib/Bio/SeqIO/fasta.pm
- lib/Bio/Tree/Statistics.pm
- t/Tree/TreeStatistics.t
I created a subroutine for the Transfer Bootstrap Expectation as defined in Lemoine et al https://www.nature.com/articles/s41586-018-0043-0.  The new subroutine is in `lib/Bio/Tree/Statistics.pm`
It is not currently correct in its output values but they are not too different than what Lemoine et al's software reports for the same tree and bootstrap trees.  
I also added a test for the transfer bootstrap expectation in `t/Tree/TreeStatistics.t`.
> transfer-bootstrap-expectation

- lib/Bio/SeqIO/swiss.pm
UniProt FT lines may have two dots connecting the positions intstead of the historic blanks. This commits allows for either format. Also new, an FT line addressing only a single residue may now be addressing this single position only.
No addressed are the specification of splice variants together with a feature, as in 
```
FT   CONFLICT        P78310-2:343
```
or
```
FT   CARBOHYD        P15151-2:360
```
or
```
FT   INIT_MET        P08195-2:1
FT   MOD_RES         P08195-2:2
```
or 
```
FT   VARIANT         Q02297-10:127
```
An initial report on this problem was erroneously posted on https://github.com/bioperl/Bio-DB-SwissProt/issues/4 .
Thanks!
Steffen
> Adjust Swiss-Prot FT A..B lines

- lib/Bio/SeqIO/fasta.pm
* the window count was off for cases where the sequence length aligned with the window size
* i also bumped up the max buffer size
> fix for writing large_fasta sequences

- .github/workflows/ci.yml
Since Travis CI is changed its terms, many FOSS projects on GitHub have started
using GitHub Actions instead. This was previously discussed at
<https://github.com/bioperl/bioperl-live/issues/224#issuecomment-1093038760>.
---
This PR is an initial working CI workflow to get started with GitHub Actions. <del>I
believe that further work can be done to enable Coveralls code coverage.</del>
<del>I can either add that in this PR or in subsequent PRs.</del>
<ins>I have added Coveralls support to this PR</ins>
> Add initial GitHub Actions workflow

- Changes
- lib/Bio/Root/Root.pm
This fixes a bug in some cases when using `SUPER::new()` such as:
```
t/SearchIO/Tiling.t .................
Error: Can't locate object method "new" via package "Bio::Search::HSP::GenericHSP::SUPER"
```
Fixes <https://github.com/bioperl/bioperl-live/issues/307>.
Connects with <https://github.com/bioperl/bioperl-live/pull/378>.
> Add minimum dependency on base.pm v2.18

- .github/workflows/ci.yml
This is per discussion at:
- <https://github.com/bioperl/bioperl-live/pull/374#discussion_r1170169873>,
- <https://github.com/bioperl/bioperl-live/issues/375>.
Uses minimum (set at 5.12), median, and latest versions.
---
Currently 5.12 is broken with the error:
```
Error: Can't locate object method "new" via package "Bio::Search::HSP::GenericHSP::SUPER" at /home/runner/work/bioperl-live/bioperl-live/blib/lib/Bio/Search/HSP/GenericHSP.pm line 182, <GEN1> line 2564.
t/SearchIO/Tiling.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1134/1141 subtests 
[...]
Test Summary Report
-------------------
t/SearchIO/Tiling.t               (Wstat: 65280 (exited 255) Tests: 7 Failed: 0)
Non-zero exit status: 255
Parse errors: Bad plan.  You planned 1141 tests but ran 7. …
```
> CI: test with minimum, median, and latest Perl versions

- Changes
- t/SeqIO/bsml_sax.t
The test `t/SeqIO/bsml_sax.t` may fail on systems with older versions of
`XML::LibXML` due to a 404 for the external BSML DTD's URL. This gives
the error:
```
http error : Unknown IO error
t/SeqIO/bsml_sax.t ..................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 14/15 subtests
```
Uses lax parser XML::SAX::PurePerl within the test which does not try to
fetch the external DTD.
Fixes <https://github.com/bioperl/bioperl-live/issues/376>.
Connects with <https://github.com/bioperl/bioperl-live/pull/379>.
> Fix bsml_sax.t by using lax SAX parser

- .github/workflows/ci.yml
This tests against specific Debian releases using all Perl module
dependencies that can be installed via `apt-get`.
This is per discussion at <https://github.com/bioperl/bioperl-live/pull/374#issuecomment-1512980823>.
---
This PR is currently blocked by the issue <https://github.com/bioperl/bioperl-live/issues/376>.
> CI: Add test jobs using Debian containers
